---
format:
  html: default
execute:
  echo: false
  warning: false
  message: false
  cache: false
toc: true
toc-depth: 4
quarto-required: '>= 1.5'
crossref:
  fig-title: '**Figur**'
  tbl-title: '**Tabell**'
  title-delim: '**.**'
  fig-prefix: figur
  tbl-prefix: tabell
lang: nb
number-sections: true
number-depth: 3
df-print: kable
fig-dpi: 900
params:
  mesos_var: campus2
  mesos_group: ~
number-offset: 0.0

---
# Svarprosent og deltakere
```{r}
#| label: 'Import data for 1_Svarprosent_'
data_1_Svarprosent_ <- qs::qread('../1_Svarprosent_/data_1_Svarprosent_.qs')
```
```{r}
source("../general_formatting.R", chdir=TRUE)
```

## Campus{#sec-Campus-69}


::: {#tbl-svarprosent-og-deltakere-campus2-chr-chr-table-target}

```{r}
table <-
	makeme(data = data_1_Svarprosent_,
		dep = c(campus2),
		type = 'chr_table_html',
		crowd='target',
		mesos_var = params$mesos_var,
		mesos_group = params$mesos_group)
gt(table[[1]])
```

_Campus_ for `{r} params$mesos_group`.

:::


## Kjønn{#sec-Kjonn-54}


::: {.panel-tabset}

## Tilbyder

::: {#fig-svarprosent-og-deltakere-s-100-fct-cat-plot-html-target}

```{r}
#| fig-height: !expr saros::fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=6)
plot <-
	makeme(data = data_1_Svarprosent_,
	dep = c(s_100),
	type='cat_plot_html',
	crowd='target',
	mesos_var = params$mesos_var,
	mesos_group = params$mesos_group)
nrange <- stringi::stri_c('N = ', n_range2(plot[[1]]))
link <- make_link(data = plot[[1]]$data)
link_plot <- make_link(data = plot, link_prefix='[PNG](', save_fn = ggsaver, file_suffix = '.png')
x <-  I(paste0(c(nrange, link, link_plot), collapse = ', '))
girafe(plot)
```

`{r} x`.

:::


## Alle andre

::: {#fig-svarprosent-og-deltakere-s-100-fct-cat-plot-html-others}

```{r}
#| fig-height: !expr saros::fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=6)
plot <-
	makeme(data = data_1_Svarprosent_,
	dep = c(s_100),
	type='cat_plot_html',
	crowd='others',
	mesos_var = params$mesos_var,
	mesos_group = params$mesos_group)
nrange <- stringi::stri_c('N = ', n_range2(plot[[1]]))
link <- make_link(data = plot[[1]]$data)
link_plot <- make_link(data = plot, link_prefix='[PNG](', save_fn = ggsaver, file_suffix = '.png')
x <-  I(paste0(c(nrange, link, link_plot), collapse = ', '))
girafe(plot)
```

`{r} x`.

:::

_Kjønn_ by __

:::


## Skoletype{#sec-Skoletype-83}


::: {.panel-tabset}

## Tilbyder

::: {#fig-svarprosent-og-deltakere-skoletype-fct-cat-plot-html-target}

```{r}
#| fig-height: !expr saros::fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=18)
plot <-
	makeme(data = data_1_Svarprosent_,
	dep = c(skoletype),
	type='cat_plot_html',
	crowd='target',
	mesos_var = params$mesos_var,
	mesos_group = params$mesos_group)
nrange <- stringi::stri_c('N = ', n_range2(plot[[1]]))
link <- make_link(data = plot[[1]]$data)
link_plot <- make_link(data = plot, link_prefix='[PNG](', save_fn = ggsaver, file_suffix = '.png')
x <-  I(paste0(c(nrange, link, link_plot), collapse = ', '))
girafe(plot)
```

`{r} x`.

:::


## Alle andre

::: {#fig-svarprosent-og-deltakere-skoletype-fct-cat-plot-html-others}

```{r}
#| fig-height: !expr saros::fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=18)
plot <-
	makeme(data = data_1_Svarprosent_,
	dep = c(skoletype),
	type='cat_plot_html',
	crowd='others',
	mesos_var = params$mesos_var,
	mesos_group = params$mesos_group)
nrange <- stringi::stri_c('N = ', n_range2(plot[[1]]))
link <- make_link(data = plot[[1]]$data)
link_plot <- make_link(data = plot, link_prefix='[PNG](', save_fn = ggsaver, file_suffix = '.png')
x <-  I(paste0(c(nrange, link, link_plot), collapse = ', '))
girafe(plot)
```

`{r} x`.

:::

_Skoletype_ by __

:::


## Svarprosent{#sec-Svarprosent-98}


::: {.panel-tabset}

## Tilbyder

::: {#fig-svarprosent-og-deltakere-svarprosent-fct-cat-plot-html-target}

```{r}
#| fig-height: !expr saros::fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=10)
plot <-
	makeme(data = data_1_Svarprosent_,
	dep = c(svarprosent),
	type='cat_plot_html',
	crowd='target',
	mesos_var = params$mesos_var,
	mesos_group = params$mesos_group)
nrange <- stringi::stri_c('N = ', n_range2(plot[[1]]))
link <- make_link(data = plot[[1]]$data)
link_plot <- make_link(data = plot, link_prefix='[PNG](', save_fn = ggsaver, file_suffix = '.png')
x <-  I(paste0(c(nrange, link, link_plot), collapse = ', '))
girafe(plot)
```

`{r} x`.

:::


## Alle andre

::: {#fig-svarprosent-og-deltakere-svarprosent-fct-cat-plot-html-others}

```{r}
#| fig-height: !expr saros::fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=10)
plot <-
	makeme(data = data_1_Svarprosent_,
	dep = c(svarprosent),
	type='cat_plot_html',
	crowd='others',
	mesos_var = params$mesos_var,
	mesos_group = params$mesos_group)
nrange <- stringi::stri_c('N = ', n_range2(plot[[1]]))
link <- make_link(data = plot[[1]]$data)
link_plot <- make_link(data = plot, link_prefix='[PNG](', save_fn = ggsaver, file_suffix = '.png')
x <-  I(paste0(c(nrange, link, link_plot), collapse = ', '))
girafe(plot)
```

`{r} x`.

:::

_Svarprosent_ by __

:::
