---
format:
  html: default
execute:
  echo: false
  warning: false
  message: false
  cache: false
toc: true
toc-depth: 4
quarto-required: '>= 1.5'
crossref:
  fig-title: '**Figur**'
  tbl-title: '**Tabell**'
  title-delim: '**.**'
  fig-prefix: figur
  tbl-prefix: tabell
lang: nb
number-sections: true
number-depth: 3
df-print: kable
fig-dpi: 900
params:
  mesos_var: campus2
  mesos_group: ~
number-offset: 3.0

---
# Svarprosent og deltakere
```{r}
#| label: 'Import data for 4_Svarprosent_'
data_4_Svarprosent_ <- qs::qread('4_Svarprosent_/data_4_Svarprosent_.qs')
```
```{r}
source("../general_formatting.R", chdir=TRUE)
```

## Aldersgrupper, inndelt{#sec-Aldersgrupper-inndelt-90}


::: {#fig-svarprosent-og-deltakere-s-7-cat-fct-cat-plot-html}

```{r, fig.height = fig_height_h_barchart(n_y=1, n_cats_y=3, max_chars_cats_y=14, multiplier_per_plot=.5)}
svarprosent_og_deltakere_s_7_cat_fct_cat_plot_html <-
	data_4_Svarprosent_ |>
		makeme(dep = c(s_7_cat),
		type = 'cat_plot_html')
nrange <- stringi::stri_c('N = ', n_range2(svarprosent_og_deltakere_s_7_cat_fct_cat_plot_html[[1]]))
link <- make_link(data = svarprosent_og_deltakere_s_7_cat_fct_cat_plot_html[[1]]$data)
link_plot <- make_link(data = svarprosent_og_deltakere_s_7_cat_fct_cat_plot_html,
		file_suffix = '.png', link_prefix='[PNG](',
		save_fn = ggsaver)
x <- I(paste0(c(nrange, link, link_plot), collapse=', '))
girafe(svarprosent_og_deltakere_s_7_cat_fct_cat_plot_html)
```

_Aldersgrupper, inndelt_. `{r} x`.

:::


## Hva er din stilling i barnehagen?{#sec-Hva-er-din-stilling-i-barnehagen--89}


::: {#fig-svarprosent-og-deltakere-s-5-fct-cat-plot-html}

```{r, fig.height = fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=19, multiplier_per_plot=.5)}
svarprosent_og_deltakere_s_5_fct_cat_plot_html <-
	data_4_Svarprosent_ |>
		makeme(dep = c(s_5),
		type = 'cat_plot_html')
nrange <- stringi::stri_c('N = ', n_range2(svarprosent_og_deltakere_s_5_fct_cat_plot_html[[1]]))
link <- make_link(data = svarprosent_og_deltakere_s_5_fct_cat_plot_html[[1]]$data)
link_plot <- make_link(data = svarprosent_og_deltakere_s_5_fct_cat_plot_html,
		file_suffix = '.png', link_prefix='[PNG](',
		save_fn = ggsaver)
x <- I(paste0(c(nrange, link, link_plot), collapse=', '))
girafe(svarprosent_og_deltakere_s_5_fct_cat_plot_html)
```

_Hva er din stilling i barnehagen?_. `{r} x`.

:::


## Hvilket kjønn er du?{#sec-Hvilket-kjonn-er-du--37}


::: {#fig-svarprosent-og-deltakere-s-43-fct-cat-plot-html}

```{r, fig.height = fig_height_h_barchart(n_y=1, n_cats_y=2, max_chars_cats_y=6, multiplier_per_plot=.5)}
svarprosent_og_deltakere_s_43_fct_cat_plot_html <-
	data_4_Svarprosent_ |>
		makeme(dep = c(s_43),
		type = 'cat_plot_html')
nrange <- stringi::stri_c('N = ', n_range2(svarprosent_og_deltakere_s_43_fct_cat_plot_html[[1]]))
link <- make_link(data = svarprosent_og_deltakere_s_43_fct_cat_plot_html[[1]]$data)
link_plot <- make_link(data = svarprosent_og_deltakere_s_43_fct_cat_plot_html,
		file_suffix = '.png', link_prefix='[PNG](',
		save_fn = ggsaver)
x <- I(paste0(c(nrange, link, link_plot), collapse=', '))
girafe(svarprosent_og_deltakere_s_43_fct_cat_plot_html)
```

_Hvilket kjønn er du?_. `{r} x`.

:::


## Svarprosent{#sec-Svarprosent-06}


::: {#fig-svarprosent-og-deltakere-svarprosent-fct-cat-plot-html}

```{r, fig.height = fig_height_h_barchart(n_y=1, n_cats_y=1, max_chars_cats_y=10, multiplier_per_plot=.5)}
svarprosent_og_deltakere_svarprosent_fct_cat_plot_html <-
	data_4_Svarprosent_ |>
		makeme(dep = c(svarprosent),
		type = 'cat_plot_html')
nrange <- stringi::stri_c('N = ', n_range2(svarprosent_og_deltakere_svarprosent_fct_cat_plot_html[[1]]))
link <- make_link(data = svarprosent_og_deltakere_svarprosent_fct_cat_plot_html[[1]]$data)
link_plot <- make_link(data = svarprosent_og_deltakere_svarprosent_fct_cat_plot_html,
		file_suffix = '.png', link_prefix='[PNG](',
		save_fn = ggsaver)
x <- I(paste0(c(nrange, link, link_plot), collapse=', '))
girafe(svarprosent_og_deltakere_svarprosent_fct_cat_plot_html)
```

_Svarprosent_. `{r} x`.

:::
